Mes 8446 dark mode technical test
dvsa/des-mobile-app pull request #1139
Opened 2023-05-05 07:22 UTC by RLCorp

## Description
Added a deactivated technical prototype of Dark mode and changed static colours to a set of custom variables.
## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2023-05-05 07:52 UTC, matthew2564 commented on src/app/pages/candidate-licence/components/licence-data-error/licence-data-error.html
> +<ion-card class="ion-text-center error-card" *ngIf="candidateDataError || candidateDataUnavailable || isOfflineError">
Why has this changed

2023-05-05 07:53 UTC, matthew2564 commented on src/app/pages/dashboard/dashboard.page.scss
> +
Why are all of these necessary?

2023-05-05 07:53 UTC, matthew2564 commented on src/app/pages/dashboard/dashboard.page.scss
> +
Same as above, I didnt think we would be changing any styles, just inverting colours.

2023-05-05 07:55 UTC, matthew2564 commented on src/app/pages/test-report/cat-home-test/test-report.cat-home-test.page.ts
> +  selector: '.test-report-cat-home-TEST-PAGE',
Please undo

2023-05-05 07:56 UTC, matthew2564 commented on src/app/pages/waiting-room-to-car/components/accompaniment-card/accompaniment-card.html
> +
Remove extra blank lines (and in ones below).

2023-05-05 07:58 UTC, matthew2564 commented on src/app/pages/waiting-room-to-car/components/accompaniment-card/accompaniment-card.ts
> +  @Input() style?: number;
What is an example value of `style`?

2023-05-05 08:03 UTC, matthew2564 commented on src/components/common/datetime-input/date-time-input.component.scss
> +  //box-shadow: inset 0 3px 3px #a5a2a2;
If not needed/wanted then please remove

2023-05-05 08:04 UTC, matthew2564 commented on src/components/common/display-address/display-address.ts
> +
Can we not use the opposing/main logic instead of hard-setting the value?

2023-05-05 08:05 UTC, matthew2564 commented on src/theme/sass-partials/_input.scss
> +  //box-shadow: inset 0 3px 3px 0 #A5A2A2;
Please remove if unused

2023-05-05 08:31 UTC, RLCorp commented on src/components/common/display-address/display-address.ts
> +
This needs to be there as the address appears both on the standard white/black background on search for completed as well as the lavender background on the communication page, where it always needs to be black in order to be readable.

2023-05-05 08:44 UTC, RLCorp commented on src/app/pages/waiting-room-to-car/components/accompaniment-card/accompaniment-card.ts
> +  @Input() style?: number;
fixed in newest commit

2023-05-05 08:44 UTC, RLCorp commented on src/app/pages/waiting-room-to-car/components/accompaniment-card/accompaniment-card.html
> +
fixed in newest commit

2023-05-05 08:44 UTC, RLCorp commented on src/app/pages/test-report/cat-home-test/test-report.cat-home-test.page.ts
> +  selector: '.test-report-cat-home-TEST-PAGE',
fixed in newest commit

2023-05-05 08:44 UTC, RLCorp commented on src/app/pages/dashboard/dashboard.page.scss
> +
fixed in newest commit

2023-05-05 08:45 UTC, RLCorp commented on src/app/pages/candidate-licence/components/licence-data-error/licence-data-error.html
> +<ion-card class="ion-text-center error-card" *ngIf="candidateDataError || candidateDataUnavailable || isOfflineError">
fixed in newest commit

2023-05-05 08:45 UTC, RLCorp commented on src/theme/sass-partials/_input.scss
> +  //box-shadow: inset 0 3px 3px 0 #A5A2A2;
fixed in newest commit

2023-05-05 08:45 UTC, RLCorp commented on src/components/common/datetime-input/date-time-input.component.scss
> +  //box-shadow: inset 0 3px 3px #a5a2a2;
fixed in newest commit

2023-05-05 09:07 UTC, RLCorp commented on src/app/pages/dashboard/dashboard.page.scss
> +
fixed in newest commit

2025-08-15 07:23 UTC, andrewsetterfield requested changes
its about time this was closed, the amount of commits that have been performed and the amount of conflicts that will have been made, this PR represents a large risk

2026-08-04 13:25 UTC, andrewsetterfield commented on src/app/pages/examiner-records/components/examiner-reports-card/examiner-reports-card.ts
> +  dataLabelBackgroundColour = '#000000';
can these not be variables so were not referencing the colour palet dirctly?

2026-08-05 09:03 UTC, andrewsetterfield approved these changes

2026-08-06 11:56 UTC, gittins7 approved these changes

2026-08-06 12:37 UTC, merged