mes-9901-chartZIndexFix
dvsa/des-mobile-app pull request #1682
Opened 2024-08-12 14:34 UTC by RLCorp

## Description
Fixed an issue where the chart's dataLabels would be displayed under the average line
## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/0c34f891-576c-4444-8786-56a8d4720b60)

2024-08-12 14:40 UTC, andrewsetterfield requested changes
rebase and remove work from other branches

2024-08-13 06:31 UTC, andrewsetterfield commented on src/components/common/chart/chart.ts
> +  createGraphLabels(dataValues: number[]): void {
So your looping though entries to push into another array to set graph labels?  could we not just use map?

2024-08-13 06:31 UTC, andrewsetterfield commented on src/components/common/chart/chart.ts
> +  createGraphLabels(dataValues: number[]): void {
i asked co-pilot

createGraphLabels(dataValues: number[]): void {
  this.graphLabels = dataValues.map((value, i) => ({
    x: this.labels[i],
    y: 0,
    marker: { size: 0 },
    label: {
      offsetY: -5,
      text: value.toString(),
      borderColor: '#FFFFFF',
      style: {
        padding: { top: -1, left: 3.5, right: 3.5 },
        fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, Roboto',
        fontSize: this.getFontSize(),
        fontWeight: 'bold',
        background: '#000000',
        color: '#FFFFFF',
      },
    },
  }));
}

2024-08-13 07:29 UTC, RLCorp commented on src/components/common/chart/chart.ts
> +  createGraphLabels(dataValues: number[]): void {
Changed in newest commit

2024-08-13 07:41 UTC, andrewsetterfield approved these changes

2024-08-13 09:33 UTC, gittins7 approved these changes

2024-08-13 09:58 UTC, merged