mes-MOTStatus
dvsa/des-mobile-app pull request #1722
Opened 2024-09-12 15:47 UTC by RLCorp

## Description
Added support for checking MOT into des
## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/13e13448-ce5e-44f8-8c00-ed1de48f357f)![image](https://github.com/user-attachments/assets/5ec6dfef-499d-41ea-b11d-61b67230ec3c)
![image](https://github.com/user-attachments/assets/1071fd51-4edc-4b9c-a78d-fbea198745bd)
![image](https://github.com/user-attachments/assets/3c905ac9-3bf8-4be0-8eb3-c5afb1623e66)
![image](https://github.com/user-attachments/assets/1147c945-72a8-4fbc-b0cf-563c18e99410)
![image](https://github.com/user-attachments/assets/da30785b-cab9-4129-882d-579031e40a56)
![image](https://github.com/user-attachments/assets/010fb156-d51c-4bff-b3a7-4b9819291ce5)
![image](https://github.com/user-attachments/assets/56bcba1b-f12e-47be-a62a-b16009ecdc16)
![image](https://github.com/user-attachments/assets/1d38096b-397c-46e3-9cec-4e435f9e97cc)
![image](https://github.com/user-attachments/assets/8b78144b-e306-4620-96bd-5f94f6a73586)
![image](https://github.com/user-attachments/assets/d21dc1e4-2539-4a2b-ae52-9eb8d0a95b8b)
![image](https://github.com/user-attachments/assets/602cee49-04b2-41d1-8b92-97813bcf11db)
![image](https://github.com/user-attachments/assets/65ee8c55-844a-4b1b-abe6-d2c90bdad792)
![image](https://github.com/user-attachments/assets/61b54411-c7e5-4255-80a0-42bbd7ec2a22)

2024-09-16 13:49 UTC, andrewsetterfield approved these changes

2024-09-17 07:02 UTC, andrewsetterfield requested changes
add this to remove my approval

2024-09-17 13:01 UTC, andrewsetterfield approved these changes

2024-09-18 07:54 UTC, gittins7 commented on src/app/pages/waiting-room-to-car/components/mot-components/alternate-mot-evidence/alternate-mot-evidence.component.ts
> +      this.formControl = null;
is there a need to set this to null before making it an untypedFormControl?

2024-09-18 07:58 UTC, gittins7 commented on src/app/pages/waiting-room-to-car/components/vehicle-registration/__tests__/vehicle-registration.spec.ts
> +    // store$ = TestBed.inject(Store);
does this need to be re-introduced or can it be deleted?

2024-09-18 08:03 UTC, gittins7 commented on src/app/shared/classes/test-flow-base-pages/office/office-base-page.ts
> +    console.log(evidence);
stray console.log()

2024-09-18 08:17 UTC, gittins7 approved these changes

2024-09-18 08:23 UTC, merged