MES-6905 VRN Waiting Room & Comms Screen
dvsa/des-mobile-app pull request #205
Opened 2021-06-17 14:00 UTC by tomcrawleyy

## Description
Introduces the VRN modal, including a button to access it on waiting room and comms screen
## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [x] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2021-06-17 14:45 UTC, Cullima requested changes
Looks good but couple of small changes required I think.  Also, can you looka t re-populating input with any previously saved value from store if re-entering page / resuming a test?

Also needs some screen grabs

2021-06-17 14:45 UTC, Cullima commented on capacitor.config.json
> +}
can you revert

2021-06-17 14:45 UTC, Cullima commented on src/components/common/vrn-capture-modal/vrn-capture-modal.scss
> +}
can you add missing line

2021-06-17 14:45 UTC, Cullima commented on src/components/common/vrn-capture-modal/vrn-capture-modal.ts
> +    this.onCancel = this.navParams.get('onCancel');
not sure this is the recommended way of passing data between page and modal.  Think we should be using `dismiss()` and `onDidDismiss()` methods (see [docs](https://ionicframework.com/docs/api/modal#dismissing-a-modal)) without need for `navParams`

2021-06-18 13:21 UTC, Cullima approved these changes

2021-06-18 13:53 UTC, gittins7 approved these changes

2021-06-18 14:02 UTC, merged