Mes 6981 wrtc page floating buttons and sizes
dvsa/des-mobile-app pull request #237
Opened 2021-07-14 09:28 UTC by gittins7

## Description
Moved bottom buttons out of footer to now be in fixed position at the bottom of the screen

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)
<img width="484" alt="Screenshot 2021-07-14 at 10 24 23" src="https://user-images.githubusercontent.com/45790769/125598599-406dc27c-be3d-4424-a006-c6dc5c8277ac.png">

<img width="619" alt="Screenshot 2021-07-14 at 10 25 02" src="https://user-images.githubusercontent.com/45790769/125598591-b9de505c-fdbf-471e-8810-359f6eddd232.png">

2021-07-14 09:34 UTC, Cullima approved these changes

2021-07-19 08:06 UTC, andrewsetterfield commented on src/app/pages/waiting-room-to-car/cat-b/waiting-room-to-car.cat-b.page.html
> -<ion-footer [hidden]="pageState.eyesightTestFailed$ | async">
are we not losing functionality here.  looks like this needs to be hidden if eyesight test failed which your removing

2021-07-19 08:09 UTC, andrewsetterfield requested changes
can my comment about eyesight be addressed

2021-07-19 09:32 UTC, andrewsetterfield approved these changes

2021-07-21 10:08 UTC, merged