MES-7438 changed order of if
dvsa/des-mobile-app pull request #384
Opened 2021-12-14 08:08 UTC by solomonsimukoko

Search for rekey - Submitted Test message display when it should be cleared

## Checklist

- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)

2021-12-14 08:13 UTC, andrewsetterfield approved these changes

2021-12-14 08:24 UTC, andrewsetterfield requested changes
um, isnt this just the same code

2021-12-14 08:27 UTC, matthew2564 commented
Can we also changed the PR title to be relevant to what the ticket is asking for, not the proposed solution please

2021-12-15 12:42 UTC, matthew2564 approved these changes

2021-12-15 12:42 UTC, andrewsetterfield approved these changes

2021-12-15 12:43 UTC, merged