mes-8354-verificationBoxFix
dvsa/des-mobile-app pull request #934
Opened 2022-11-08 15:26 UTC by RLCorp

## Description
Fixed verification box not displaying properly on modal
## Checklist

- [x] PR title includes the JIRA ticket number
- [x] Branch is rebased against the latest develop
- [x] Code has been tested manually
- [x] PR link added to JIRA ticket
- [ ] One review from each scrum team
- [ ] Squashed commit contains the JIRA ticket number

## Screenshots (optional)
<img width="449" alt="image" src="https://user-images.githubusercontent.com/88314925/200605716-280125ef-4022-4e53-845b-2ec37eea3b2d.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/88314925/201042657-2f013241-2908-411a-afaa-3711293f27aa.png">

2022-11-08 15:40 UTC, gittins7 approved these changes

2022-11-09 09:41 UTC, andrewsetterfield requested changes
this is all VRM capture?  that wasnt the issue.  it was broken through means the user cant use.  The bug was on Mod1 not VRM

2022-11-10 09:39 UTC, andrewsetterfield approved these changes

2022-11-10 09:40 UTC, matthew2564 approved these changes

2022-11-10 09:41 UTC, merged